### ISSUE TITLE
error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project

### ISSUE THREAD

**Issue by mfkl** [xamarin/Xamarin.Legacy.Sdk#33]
Hi,

Thanks for this, I hope I manage to make it work with LVS (https://github.com/mfkl/libvlcsharp/commits/net6-xamarin-legacy-sdk).

So far, no luck though: `error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project`. That's with only

```
<TargetFrameworks>net6.0;monoandroid11.0</TargetFrameworks>
```

The only difference I'm seeing with your CI setup is that I'm using the .NET 6 stable SDK version. Surely that should not be the problem... I observe the same error when trying to build the samples from this repo locally.

I've noticed https://github.com/xamarin/Xamarin.Legacy.Sdk/commit/5d9facb215e240e295004b1f0faf94efd40bc976 but still investigating why I'm running into error this while this seems to have been fixed already.

Since I have uap targets, it seems I'll need to run msbuild as well anyway (uap targets are likely not in scope of this project).

**Comment by jonathanpeppers** [comment]
I pushed a release to NuGet.org with the fix: https://www.nuget.org/packages/Xamarin.Legacy.Sdk/0.1.2-alpha6

**Comment by mfkl** [comment]
Thanks, will try it out. Though I will likely have to stick to MSBuild, as I would like to build tvOS and UAP targets as well in one go.

**Comment by borrrden** [comment]
I still get this with 0.2.0-alpha2 when using dotnet build.  MSBuild works ok for ios at least.

**Comment by jonathanpeppers** [comment]
@borrrden can you file a new issue and attach a `.binlog`? Adding `-bl` at the command-line will create a `msbuild.binlog` file in the current directory.
